// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: proto/replication.proto

package razpravljalnica

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplicateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateUserRequest) Reset() {
	*x = ReplicateUserRequest{}
	mi := &file_proto_replication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateUserRequest) ProtoMessage() {}

func (x *ReplicateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateUserRequest.ProtoReflect.Descriptor instead.
func (*ReplicateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{0}
}

func (x *ReplicateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type ReplicateTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         *Topic                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateTopicRequest) Reset() {
	*x = ReplicateTopicRequest{}
	mi := &file_proto_replication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateTopicRequest) ProtoMessage() {}

func (x *ReplicateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateTopicRequest.ProtoReflect.Descriptor instead.
func (*ReplicateTopicRequest) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{1}
}

func (x *ReplicateTopicRequest) GetTopic() *Topic {
	if x != nil {
		return x.Topic
	}
	return nil
}

type ReplicateMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateMessageRequest) Reset() {
	*x = ReplicateMessageRequest{}
	mi := &file_proto_replication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateMessageRequest) ProtoMessage() {}

func (x *ReplicateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateMessageRequest.ProtoReflect.Descriptor instead.
func (*ReplicateMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{2}
}

func (x *ReplicateMessageRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type ReplicateLikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NewLikeCount  int32                  `protobuf:"varint,3,opt,name=new_like_count,json=newLikeCount,proto3" json:"new_like_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateLikeRequest) Reset() {
	*x = ReplicateLikeRequest{}
	mi := &file_proto_replication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateLikeRequest) ProtoMessage() {}

func (x *ReplicateLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateLikeRequest.ProtoReflect.Descriptor instead.
func (*ReplicateLikeRequest) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{3}
}

func (x *ReplicateLikeRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *ReplicateLikeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReplicateLikeRequest) GetNewLikeCount() int32 {
	if x != nil {
		return x.NewLikeCount
	}
	return 0
}

type UpdateSuccessorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Successor     *NodeInfo              `protobuf:"bytes,1,opt,name=successor,proto3" json:"successor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSuccessorRequest) Reset() {
	*x = UpdateSuccessorRequest{}
	mi := &file_proto_replication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSuccessorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSuccessorRequest) ProtoMessage() {}

func (x *UpdateSuccessorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSuccessorRequest.ProtoReflect.Descriptor instead.
func (*UpdateSuccessorRequest) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSuccessorRequest) GetSuccessor() *NodeInfo {
	if x != nil {
		return x.Successor
	}
	return nil
}

type UpdatePredecessorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Predecessor   *NodeInfo              `protobuf:"bytes,1,opt,name=predecessor,proto3" json:"predecessor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePredecessorRequest) Reset() {
	*x = UpdatePredecessorRequest{}
	mi := &file_proto_replication_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePredecessorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePredecessorRequest) ProtoMessage() {}

func (x *UpdatePredecessorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePredecessorRequest.ProtoReflect.Descriptor instead.
func (*UpdatePredecessorRequest) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePredecessorRequest) GetPredecessor() *NodeInfo {
	if x != nil {
		return x.Predecessor
	}
	return nil
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_replication_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{6}
}

func (x *PingResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type FullStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Topics        []*Topic               `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	Messages      []*Message             `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullStateResponse) Reset() {
	*x = FullStateResponse{}
	mi := &file_proto_replication_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullStateResponse) ProtoMessage() {}

func (x *FullStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullStateResponse.ProtoReflect.Descriptor instead.
func (*FullStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{7}
}

func (x *FullStateResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *FullStateResponse) GetTopics() []*Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *FullStateResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *NodeInfo              `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_proto_replication_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterNodeRequest) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ChainInfo     *ChainInfoResponse     `protobuf:"bytes,3,opt,name=chain_info,json=chainInfo,proto3" json:"chain_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_proto_replication_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterNodeResponse) GetChainInfo() *ChainInfoResponse {
	if x != nil {
		return x.ChainInfo
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_replication_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ChainInfoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Head           *NodeInfo              `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Tail           *NodeInfo              `protobuf:"bytes,2,opt,name=tail,proto3" json:"tail,omitempty"`
	AllNodes       []*NodeInfo            `protobuf:"bytes,3,rep,name=all_nodes,json=allNodes,proto3" json:"all_nodes,omitempty"`
	NodeSuccessors map[string]string      `protobuf:"bytes,4,rep,name=node_successors,json=nodeSuccessors,proto3" json:"node_successors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // node_id -> successor_node_id
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChainInfoResponse) Reset() {
	*x = ChainInfoResponse{}
	mi := &file_proto_replication_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainInfoResponse) ProtoMessage() {}

func (x *ChainInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_replication_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainInfoResponse.ProtoReflect.Descriptor instead.
func (*ChainInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_replication_proto_rawDescGZIP(), []int{11}
}

func (x *ChainInfoResponse) GetHead() *NodeInfo {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *ChainInfoResponse) GetTail() *NodeInfo {
	if x != nil {
		return x.Tail
	}
	return nil
}

func (x *ChainInfoResponse) GetAllNodes() []*NodeInfo {
	if x != nil {
		return x.AllNodes
	}
	return nil
}

func (x *ChainInfoResponse) GetNodeSuccessors() map[string]string {
	if x != nil {
		return x.NodeSuccessors
	}
	return nil
}

var File_proto_replication_proto protoreflect.FileDescriptor

const file_proto_replication_proto_rawDesc = "" +
	"\n" +
	"\x17proto/replication.proto\x12\x0frazpravljalnica\x1a\x1bproto/razpravljalnica.proto\x1a\x1bgoogle/protobuf/empty.proto\"A\n" +
	"\x14ReplicateUserRequest\x12)\n" +
	"\x04user\x18\x01 \x01(\v2\x15.razpravljalnica.UserR\x04user\"E\n" +
	"\x15ReplicateTopicRequest\x12,\n" +
	"\x05topic\x18\x01 \x01(\v2\x16.razpravljalnica.TopicR\x05topic\"M\n" +
	"\x17ReplicateMessageRequest\x122\n" +
	"\amessage\x18\x01 \x01(\v2\x18.razpravljalnica.MessageR\amessage\"t\n" +
	"\x14ReplicateLikeRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12$\n" +
	"\x0enew_like_count\x18\x03 \x01(\x05R\fnewLikeCount\"Q\n" +
	"\x16UpdateSuccessorRequest\x127\n" +
	"\tsuccessor\x18\x01 \x01(\v2\x19.razpravljalnica.NodeInfoR\tsuccessor\"W\n" +
	"\x18UpdatePredecessorRequest\x12;\n" +
	"\vpredecessor\x18\x01 \x01(\v2\x19.razpravljalnica.NodeInfoR\vpredecessor\"?\n" +
	"\fPingResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xa6\x01\n" +
	"\x11FullStateResponse\x12+\n" +
	"\x05users\x18\x01 \x03(\v2\x15.razpravljalnica.UserR\x05users\x12.\n" +
	"\x06topics\x18\x02 \x03(\v2\x16.razpravljalnica.TopicR\x06topics\x124\n" +
	"\bmessages\x18\x03 \x03(\v2\x18.razpravljalnica.MessageR\bmessages\"D\n" +
	"\x13RegisterNodeRequest\x12-\n" +
	"\x04node\x18\x01 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04node\"\x8d\x01\n" +
	"\x14RegisterNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12A\n" +
	"\n" +
	"chain_info\x18\x03 \x01(\v2\".razpravljalnica.ChainInfoResponseR\tchainInfo\"+\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\xcd\x02\n" +
	"\x11ChainInfoResponse\x12-\n" +
	"\x04head\x18\x01 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04head\x12-\n" +
	"\x04tail\x18\x02 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04tail\x126\n" +
	"\tall_nodes\x18\x03 \x03(\v2\x19.razpravljalnica.NodeInfoR\ballNodes\x12_\n" +
	"\x0fnode_successors\x18\x04 \x03(\v26.razpravljalnica.ChainInfoResponse.NodeSuccessorsEntryR\x0enodeSuccessors\x1aA\n" +
	"\x13NodeSuccessorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xdc\x05\n" +
	"\x12ReplicationService\x12N\n" +
	"\rReplicateUser\x12%.razpravljalnica.ReplicateUserRequest\x1a\x16.google.protobuf.Empty\x12P\n" +
	"\x0eReplicateTopic\x12&.razpravljalnica.ReplicateTopicRequest\x1a\x16.google.protobuf.Empty\x12T\n" +
	"\x10ReplicateMessage\x12(.razpravljalnica.ReplicateMessageRequest\x1a\x16.google.protobuf.Empty\x12N\n" +
	"\rReplicateLike\x12%.razpravljalnica.ReplicateLikeRequest\x1a\x16.google.protobuf.Empty\x12R\n" +
	"\x0fUpdateSuccessor\x12'.razpravljalnica.UpdateSuccessorRequest\x1a\x16.google.protobuf.Empty\x12V\n" +
	"\x11UpdatePredecessor\x12).razpravljalnica.UpdatePredecessorRequest\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x1d.razpravljalnica.PingResponse\x12J\n" +
	"\fGetFullState\x12\x16.google.protobuf.Empty\x1a\".razpravljalnica.FullStateResponse\x12G\n" +
	"\tSyncState\x12\".razpravljalnica.FullStateResponse\x1a\x16.google.protobuf.Empty2\x81\x02\n" +
	"\x0eNodeManagement\x12[\n" +
	"\fRegisterNode\x12$.razpravljalnica.RegisterNodeRequest\x1a%.razpravljalnica.RegisterNodeResponse\x12F\n" +
	"\tHeartbeat\x12!.razpravljalnica.HeartbeatRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\fGetChainInfo\x12\x16.google.protobuf.Empty\x1a\".razpravljalnica.ChainInfoResponseB\x12Z\x10/razpravljalnicab\x06proto3"

var (
	file_proto_replication_proto_rawDescOnce sync.Once
	file_proto_replication_proto_rawDescData []byte
)

func file_proto_replication_proto_rawDescGZIP() []byte {
	file_proto_replication_proto_rawDescOnce.Do(func() {
		file_proto_replication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_replication_proto_rawDesc), len(file_proto_replication_proto_rawDesc)))
	})
	return file_proto_replication_proto_rawDescData
}

var file_proto_replication_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_replication_proto_goTypes = []any{
	(*ReplicateUserRequest)(nil),     // 0: razpravljalnica.ReplicateUserRequest
	(*ReplicateTopicRequest)(nil),    // 1: razpravljalnica.ReplicateTopicRequest
	(*ReplicateMessageRequest)(nil),  // 2: razpravljalnica.ReplicateMessageRequest
	(*ReplicateLikeRequest)(nil),     // 3: razpravljalnica.ReplicateLikeRequest
	(*UpdateSuccessorRequest)(nil),   // 4: razpravljalnica.UpdateSuccessorRequest
	(*UpdatePredecessorRequest)(nil), // 5: razpravljalnica.UpdatePredecessorRequest
	(*PingResponse)(nil),             // 6: razpravljalnica.PingResponse
	(*FullStateResponse)(nil),        // 7: razpravljalnica.FullStateResponse
	(*RegisterNodeRequest)(nil),      // 8: razpravljalnica.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),     // 9: razpravljalnica.RegisterNodeResponse
	(*HeartbeatRequest)(nil),         // 10: razpravljalnica.HeartbeatRequest
	(*ChainInfoResponse)(nil),        // 11: razpravljalnica.ChainInfoResponse
	nil,                              // 12: razpravljalnica.ChainInfoResponse.NodeSuccessorsEntry
	(*User)(nil),                     // 13: razpravljalnica.User
	(*Topic)(nil),                    // 14: razpravljalnica.Topic
	(*Message)(nil),                  // 15: razpravljalnica.Message
	(*NodeInfo)(nil),                 // 16: razpravljalnica.NodeInfo
	(*emptypb.Empty)(nil),            // 17: google.protobuf.Empty
}
var file_proto_replication_proto_depIdxs = []int32{
	13, // 0: razpravljalnica.ReplicateUserRequest.user:type_name -> razpravljalnica.User
	14, // 1: razpravljalnica.ReplicateTopicRequest.topic:type_name -> razpravljalnica.Topic
	15, // 2: razpravljalnica.ReplicateMessageRequest.message:type_name -> razpravljalnica.Message
	16, // 3: razpravljalnica.UpdateSuccessorRequest.successor:type_name -> razpravljalnica.NodeInfo
	16, // 4: razpravljalnica.UpdatePredecessorRequest.predecessor:type_name -> razpravljalnica.NodeInfo
	13, // 5: razpravljalnica.FullStateResponse.users:type_name -> razpravljalnica.User
	14, // 6: razpravljalnica.FullStateResponse.topics:type_name -> razpravljalnica.Topic
	15, // 7: razpravljalnica.FullStateResponse.messages:type_name -> razpravljalnica.Message
	16, // 8: razpravljalnica.RegisterNodeRequest.node:type_name -> razpravljalnica.NodeInfo
	11, // 9: razpravljalnica.RegisterNodeResponse.chain_info:type_name -> razpravljalnica.ChainInfoResponse
	16, // 10: razpravljalnica.ChainInfoResponse.head:type_name -> razpravljalnica.NodeInfo
	16, // 11: razpravljalnica.ChainInfoResponse.tail:type_name -> razpravljalnica.NodeInfo
	16, // 12: razpravljalnica.ChainInfoResponse.all_nodes:type_name -> razpravljalnica.NodeInfo
	12, // 13: razpravljalnica.ChainInfoResponse.node_successors:type_name -> razpravljalnica.ChainInfoResponse.NodeSuccessorsEntry
	0,  // 14: razpravljalnica.ReplicationService.ReplicateUser:input_type -> razpravljalnica.ReplicateUserRequest
	1,  // 15: razpravljalnica.ReplicationService.ReplicateTopic:input_type -> razpravljalnica.ReplicateTopicRequest
	2,  // 16: razpravljalnica.ReplicationService.ReplicateMessage:input_type -> razpravljalnica.ReplicateMessageRequest
	3,  // 17: razpravljalnica.ReplicationService.ReplicateLike:input_type -> razpravljalnica.ReplicateLikeRequest
	4,  // 18: razpravljalnica.ReplicationService.UpdateSuccessor:input_type -> razpravljalnica.UpdateSuccessorRequest
	5,  // 19: razpravljalnica.ReplicationService.UpdatePredecessor:input_type -> razpravljalnica.UpdatePredecessorRequest
	17, // 20: razpravljalnica.ReplicationService.Ping:input_type -> google.protobuf.Empty
	17, // 21: razpravljalnica.ReplicationService.GetFullState:input_type -> google.protobuf.Empty
	7,  // 22: razpravljalnica.ReplicationService.SyncState:input_type -> razpravljalnica.FullStateResponse
	8,  // 23: razpravljalnica.NodeManagement.RegisterNode:input_type -> razpravljalnica.RegisterNodeRequest
	10, // 24: razpravljalnica.NodeManagement.Heartbeat:input_type -> razpravljalnica.HeartbeatRequest
	17, // 25: razpravljalnica.NodeManagement.GetChainInfo:input_type -> google.protobuf.Empty
	17, // 26: razpravljalnica.ReplicationService.ReplicateUser:output_type -> google.protobuf.Empty
	17, // 27: razpravljalnica.ReplicationService.ReplicateTopic:output_type -> google.protobuf.Empty
	17, // 28: razpravljalnica.ReplicationService.ReplicateMessage:output_type -> google.protobuf.Empty
	17, // 29: razpravljalnica.ReplicationService.ReplicateLike:output_type -> google.protobuf.Empty
	17, // 30: razpravljalnica.ReplicationService.UpdateSuccessor:output_type -> google.protobuf.Empty
	17, // 31: razpravljalnica.ReplicationService.UpdatePredecessor:output_type -> google.protobuf.Empty
	6,  // 32: razpravljalnica.ReplicationService.Ping:output_type -> razpravljalnica.PingResponse
	7,  // 33: razpravljalnica.ReplicationService.GetFullState:output_type -> razpravljalnica.FullStateResponse
	17, // 34: razpravljalnica.ReplicationService.SyncState:output_type -> google.protobuf.Empty
	9,  // 35: razpravljalnica.NodeManagement.RegisterNode:output_type -> razpravljalnica.RegisterNodeResponse
	17, // 36: razpravljalnica.NodeManagement.Heartbeat:output_type -> google.protobuf.Empty
	11, // 37: razpravljalnica.NodeManagement.GetChainInfo:output_type -> razpravljalnica.ChainInfoResponse
	26, // [26:38] is the sub-list for method output_type
	14, // [14:26] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_replication_proto_init() }
func file_proto_replication_proto_init() {
	if File_proto_replication_proto != nil {
		return
	}
	file_proto_razpravljalnica_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_replication_proto_rawDesc), len(file_proto_replication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_replication_proto_goTypes,
		DependencyIndexes: file_proto_replication_proto_depIdxs,
		MessageInfos:      file_proto_replication_proto_msgTypes,
	}.Build()
	File_proto_replication_proto = out.File
	file_proto_replication_proto_goTypes = nil
	file_proto_replication_proto_depIdxs = nil
}
